services:
  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - log-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wordpress.rule=Host(`pipeline.inqubi.eu`)'
      - 'traefik.http.services.wordpress.loadbalancer.server.port=4000'
      - 'traefik.http.routers.wordpress.tls.certresolver=letsencrypt'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.wordpress.middlewares=redirect-to-https'
    networks:
      - log-net

networks:
  log-net:
    driver: bridge
  default:
    external:
      name: traefik_network
