services:
  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - log-net
      - traefik_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    env_file:
      - .env
    labels:
      # Enable Traefik for this service
      - 'traefik.enable=true'

      # HTTP -> HTTPS Redirection
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.api-http.rule=Host("pipeline.inqubi.eu")'
      - 'traefik.http.routers.api-http.entrypoints=http'
      - 'traefik.http.routers.api-http.middlewares=redirect-to-https'

      # HTTPS Router
      - 'traefik.http.routers.api.rule=Host("pipeline.inqubi.eu")'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.tls.certresolver=letsencrypt'

      # Backend service port
      - 'traefik.http.services.api.loadbalancer.server.port=${SERVER_PORT}'
    networks:
      - log-net
      - traefik_network

networks:
  log-net:
    driver: bridge
  traefik_network:
    external: true
