services:
  db:
    image: postgres:latest
    container_name: log
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    # volumes:
    #   - ./data:/var/lib/postgresql/data

  api:
    image: log-api:latest
    container_name: api
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    env_file:
      - .env
