services:
  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - log-net
      - proxy-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - log-net
      - proxy-net

networks:
  log-net:
    driver: bridge
  proxy-net:
    external: true
